### ISSUE TITLE
AI Player

### ISSUE THREAD

**Issue by MichaelRRyan** [MichaelRRyan/Mecha-Miners#38]
Create a simple AI player that can play each part of the currently available game. 

The AI has a number of behaviour **states** (patrol, pursue, attack, mine, etc.) which all listen to different signals from the AI's many **senses**. The AI can select which senses to use (automatically turning off all other senses) and then listen to particular signals on each or use them in different ways. The AI switches to different states based on any number of things.

- [x] Player instances can be created and updated without taking keyboard input. #36 
- [x] The AI should use a finite state machine/behaviour tree under the hood.
- [x] The AI should be able to path-find to a location.
- [x] The AI should mine gems within a range. #41
- [x] The AI should explore and descend the caves. #42
- [x] Miner Bots should use a mining beam instead of a drill.
- [x] The AI should avoid entities using obstacle avoidance.
- [x] The AI should assess when another entity is harvesting a resource.
- [x] The AI should pursue and harvest resources at the same time.
- [x] The AI should prioritise spotted resources by distance.
- [x] The AI's behaviour should be reset when it dies.
- [x] The AI should have a randomly generated Bravado stat.
- [x] The AI should attack or flee from threats.
- [ ] The AI should return their resources to the ship once they get enough of them. #62
